version: 2

jobs:
    build:
        docker:
            - image: circleci/node:8

        working_directory: ~/brand-namer

        steps:
            - checkout

            # - run: sudo npm install -g bs-platform
            - run: yarn global add bs-platform

            # Download and cache dependencies
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package.json" }}
                # fallback to using the latest cache if no exact match is found
                - v1-dependencies-
            - run: yarn install
            - save_cache:
                paths:
                    - ./node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
            - run: 
                name: Start
                command: yarn run start
                environment:
                    APP_PORT: 3000
                    GCOULD_TRANSLATE_KEY: "your-key"
            - run: yarn test
