defaults:
    working_directory: /tmp
    docker:
        - image: circleci/node:8.9.4

version: 2

jobs:
    client:
        <<: *defaults
        steps:
            - checkout
            - run: cd ./client/
            # Download and cache dependencies
            - restore_cache:
                keys:
                - v1-client-dependencies-{{ checksum "package.json" }}
                # fallback to using the latest cache if no exact match is found
                - v1-client-dependencies-
            - run: yarn install
            - save_cache:
                paths:
                    - node_modules
                key: v1-client-dependencies-{{ checksum "package.json" }}
            - run: yarn test

    api:
        <<: *defaults
        steps:
            - checkout
            - run: cd ./api/
            # Download and cache dependencies
            - restore_cache:
                keys:
                - v1-api-dependencies-{{ checksum "package.json" }}
                # fallback to using the latest cache if no exact match is found
                - v1-api-dependencies-
            - run: yarn install
            - save_cache:
                paths:
                    - node_modules
                key: v1-api-dependencies-{{ checksum "package.json" }}
            - run: yarn test
