version: 2

jobs:
    build:
        docker:
            - image: circleci/node:8.9.4

        working_directory: ~/brand-namer

        steps:
            - checkout

            # - run: sudo npm install -g bs-platform
            - run: yarn global add bs-platform

            # Client build
            # Download and cache dependencies
            - restore_cache:
                keys:
                - v1-client-dependencies-{{ checksum "client/package.json" }}
                # fallback to using the latest cache if no exact match is found
                - v1-client-dependencies-
            - run: cd ./client/ && yarn install
            - save_cache:
                paths:
                    - ./client/node_modules
                key: v1-client-dependencies-{{ checksum "client/package.json" }}
            - run: cd ./client/ && yarn run start
            - run: cd ./client/ && yarn test

            # Api build
            # Download and cache dependencies
            - restore_cache:
                keys:
                - v1-api-dependencies-{{ checksum "api/package.json" }}
                # fallback to using the latest cache if no exact match is found
                - v1-api-dependencies-
            - run: cd ./api/ && yarn install
            - save_cache:
                paths:
                    - ./api/node_modules
                key: v1-api-dependencies-{{ checksum "api/package.json" }}
            - run: cd ./api/ && yarn run build
            - run: cd ./api/ && yarn test
